{% set name = "RigolWFM" %}
{% set version = "0.9.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/RigolWFM-{{ version }}.tar.gz
  sha256: 85ae9dafd7e6d4b826fa73d7180e61610d563392869a2abbae24d827cb84895b

build:
  entry_points:
    - wfmconvert = RigolWFM.wfmconvert:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools >=44
  run:
    - kaitaistruct
    - matplotlib-base
    - numpy
    - python >=3.6
    - requests

test:
  imports:
    - RigolWFM
  commands:
    - pip check
    - wfmconvert --help
  requires:
    - pip

about:
  home: https://github.com/scottprahl/RigolWFM
  summary: |
    A comprehensive resource for interpreting waveform ``.wmf`` files created
    by any Rigol oscilloscope.

  license: BSD-3-Clause
  license_family: BSD
  license_file:
    - LICENSE
  doc_url: https://RigolWFM.readthedocs.io/
  dev_url: https://github.com/scottprahl/RigolWFM

extra:
  recipe-maintainers:
    - scottprahl
